global:
  resolve_timeout: 2m
  slack_api_url: '<your slack api url here>'
route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#<desired channel here>'
    send_resolved: true
